name: Prepare Release Docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.2, v1.0.3.rc-0, etc)'
        required: true

jobs:
  update-release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run release docs updater
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: node dev/update-release-docs.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update release-docs.json for ${{ github.event.release.tag_name }}" || echo "Nothing to commit"
          git push origin HEAD:main
