name: Update Release Docs

on:
  release:
    types: [published]

jobs:
  update-release-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run release docs updater
        env:
          VERSION: ${{ github.event.release.tag_name }}
          DATE: ${{ github.event.release.published_at }}
          BODY: ${{ github.event.release.body }}
        run: node dev/update-release-docs.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update release-docs.json for ${{ github.event.release.tag_name }}"
          git push
